# Generated by Django 3.0.2 on 2020-02-07 10:29

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=30, verbose_name='简历名称')),
                ('is_open', models.IntegerField(choices=[(0, '不公开'), (1, '公开')], default=0, verbose_name='是否公开')),
                ('username', models.CharField(max_length=10, verbose_name='简历用户名')),
                ('pic', models.ImageField(upload_to='resumes/', verbose_name='照片')),
                ('experience', models.IntegerField(default=0, verbose_name='工作经验')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('status', models.IntegerField(choices=[(1, '在职'), (0, '离职')], default=0, verbose_name='状态')),
                ('start_working', models.DateField(blank=True, null=True, verbose_name='开始工作时间')),
                ('addr', models.CharField(max_length=30, verbose_name='地址')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('ID_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('annual_income', models.IntegerField(blank=True, null=True, verbose_name='年收入/万（元）')),
                ('hukou_or_nationality', models.CharField(blank=True, max_length=20, null=True, verbose_name='户口/国籍')),
                ('marital_status', models.IntegerField(choices=[(0, '未婚'), (1, '已婚')], default=0, verbose_name='婚姻状况')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
            },
        ),
        migrations.CreateModel(
            name='ResumeWorking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('company', models.CharField(max_length=30, verbose_name='公司')),
                ('position', models.CharField(max_length=20, verbose_name='职位')),
                ('job_description', DjangoUeditor.models.UEditorField(blank=True, verbose_name='工作描述')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='行业')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='部门')),
                ('nature', models.CharField(blank=True, max_length=30, null=True, verbose_name='性质')),
                ('other', models.CharField(blank=True, max_length=30, null=True, verbose_name='其他')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='类型')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
            options={
                'verbose_name': '工作经验',
                'verbose_name_plural': '工作经验',
            },
        ),
        migrations.CreateModel(
            name='ResumeProjectExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('project_description', DjangoUeditor.models.UEditorField(blank=True, verbose_name='项目描述')),
                ('responsibility_description', DjangoUeditor.models.UEditorField(blank=True, verbose_name='责任描述')),
                ('affiliated_company', models.CharField(blank=True, max_length=30, null=True, verbose_name='所属公司')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
            options={
                'verbose_name': '项目经验',
                'verbose_name_plural': '项目经验',
            },
        ),
        migrations.CreateModel(
            name='ResumeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('place', models.CharField(max_length=30, verbose_name='地点')),
                ('function', DjangoUeditor.models.UEditorField(blank=True, verbose_name='职能')),
                ('pay_type', models.IntegerField(choices=[(1, '月薪'), (2, '年薪')], default=1, verbose_name='薪资类型')),
                ('salary_expectation', models.IntegerField(verbose_name='期望薪资')),
                ('work_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='工作类型')),
                ('industry', models.CharField(blank=True, max_length=30, null=True, verbose_name='行业')),
                ('arrival_time', models.IntegerField(choices=[(1, '随时'), (2, '一周内'), (3, '一个月内')], default=1, verbose_name='到岗时间')),
                ('self_evaluation', DjangoUeditor.models.UEditorField(blank=True, verbose_name='自我评价')),
                ('personal_tags', models.CharField(blank=True, max_length=30, null=True, verbose_name='个人标签')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
            options={
                'verbose_name': '求职意向',
                'verbose_name_plural': '求职意向',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('enrollment_time', models.DateField(verbose_name='入学时间')),
                ('graduation_time', models.DateField(verbose_name='毕业时间')),
                ('school', models.CharField(max_length=30, verbose_name='学校')),
                ('education', models.IntegerField(choices=[(1, '高中'), (2, '大专'), (3, '本科'), (4, '硕士')], verbose_name='学历')),
                ('major', models.CharField(max_length=30, verbose_name='专业')),
                ('major_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业描述')),
                ('is_overseas_study', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否留学')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.Resume')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
    ]
