# Generated by Django 2.2.6 on 2020-01-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='update_time',
        ),
    ]
